Source/Pages/Issues/All.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DrakeLambert.Peerra.Data;
using DrakeLambert.Peerra.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace DrakeLambert.Peerra.Pages.Issues
{
    [Authorize]
    public class AllModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public List<Issue> MyIssues { get; set; }

        public List<Issue> OthersIssues { get; set; }

        public AllModel(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToPage("/Error");
            }

            

            OthersIssues = await _context.HelpRequests.Include(hr => hr.Issue).Where(hr => hr.HelperId == user.Id).Where(hr => hr.Status != HelpRequestStatus.Declined).Select(hr => hr.Issue).ToListAsync();

            MyIssues = await _context.Issues.Include(i => i.HelpRequests).Where(i => i.OwnerId == user.Id).OrderBy(i => i.IsSolved).ToListAsync();

            return Page();
        }
    }
}

Source/Pages/Issues/New.cshtml.cs
using System;
using System.Threading.Tasks;
using DrakeLambert.Peerra.Data;
using DrakeLambert.Peerra.Entities;
using DrakeLambert.Peerra.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace DrakeLambert.Peerra.Pages.Issues
{
    [Authorize]
    public class NewModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<NewModel> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHelpRequestService _helpRequestService;

        public Topic ParentTopic { get; set; }

        [BindProperty]
        public Issue NewIssue { get; set; }

        public NewModel(ApplicationDbContext context, ILogger<NewModel> logger, UserManager<ApplicationUser> userManager, IHelpRequestService helpRequestService)
        {
            _context = context;
            _logger = logger;
            _userManager = userManager;
            _helpRequestService = helpRequestService;
        }

        public async Task<IActionResult> OnGetAsync([FromRoute] Guid id)
        {
            if (id != Guid.Empty)
            {
                ParentTopic = await _context.Topics.FindAsync(id);
                if (ParentTopic == null)
                {
                    return RedirectToPage("/NotFound", new { message = "We couldn't find the parent topic from your link. This may be because the topic has been deleted. You can use the topic search on the home page to try to find it again." });
                }
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync([FromRoute] Guid id)
        {
            if (id != Guid.Empty)
            {
                ParentTopic = await _context.Topics.FindAsync(id);
                if (ParentTopic == null)
                {
                    return RedirectToPage("/NotFound", new { message = "We couldn't find the parent topic from your link. This may be because the topic has been deleted. You can use the topic search on the home page to try to find it again." });
                }
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToPage("/Error");
            }

            NewIssue.OwnerId = user.Id;

            NewIssue.TopicId = id;

            _context.Issues.Add(NewIssue);

            await _context.SaveChangesAsync();

            await _helpRequestService.RequestHelpAsync(NewIssue);

            return RedirectToPage("Single", new { Id = NewIssue.Id });
        }
    }
}

Source/Pages/Issues/Peer.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using DrakeLambert.Peerra.Data;
using DrakeLambert.Peerra.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace DrakeLambert.Peerra.Pages.Issues
{
	public class PeerModel : PageModel
	{
		private readonly ApplicationDbContext _context;
		private readonly SignInManager<ApplicationUser> _signInManager;

		public Issue Issue { get; set; }

		public HelpRequest UserHelpRequest { get; set; }

		public PeerModel(ApplicationDbContext context, SignInManager<ApplicationUser> signInManager)
		{
			_context = context;
			_signInManager = signInManager;
		}

		public async Task<IActionResult> OnGetAsync([FromRoute] Guid id)
		{
			Issue = await _context.Issues
				.Include(i => i.HelpRequests)
					.ThenInclude(hr => hr.Helper)
				.Include(i => i.Owner)
				.Include(i => i.Topic)
				.SingleOrDefaultAsync(i => i.Id == id);

			if (Issue == null)
			{
				return RedirectToPage("/NotFound", new { message = "This issue may have been removed or moved." });
			}

			if (_signInManager.IsSignedIn(User))
			{
				var user = await _signInManager.UserManager.GetUserAsync(User);
				if (user.Id == Issue.OwnerId)
				{
					return RedirectToPage("/Issues/Single", new { id = id });
				}

				UserHelpRequest = Issue.HelpRequests.SingleOrDefault(hr => hr.HelperId == user.Id);
			}

			return Page();
		}

		[Authorize]
		public async Task<IActionResult> OnPostDeclineAsync([FromRoute] Guid id)
		{
			Issue = await _context.Issues
							.Include(i => i.HelpRequests)
								.ThenInclude(hr => hr.Helper)
							.Include(i => i.Owner)
							.Include(i => i.Topic)
							.SingleOrDefaultAsync(i => i.Id == id);

			if (Issue == null)
			{
				return RedirectToPage("/NotFound", new { message = "This issue may have been removed or moved." });
			}

			var user = await _signInManager.UserManager.GetUserAsync(User);

			if (user.Id == Issue.OwnerId)
			{
				return RedirectToPage("/Issues/Single", new { id = id });
			}

			UserHelpRequest = Issue.HelpRequests.SingleOrDefault(hr => hr.HelperId == user.Id);

			if (UserHelpRequest == null)
			{
				UserHelpRequest = new HelpRequest
				{
					Helper = user,
					Issue = Issue
				};

				Issue.HelpRequests.Add(UserHelpRequest);
			}

			UserHelpRequest.Status = HelpRequestStatus.Declined;

			await _context.SaveChangesAsync();

			return Page();
		}
	}
}

Source/Pages/Issues/Peers.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using DrakeLambert.Peerra.Data;
using DrakeLambert.Peerra.Entities;
using DrakeLambert.Peerra.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DrakeLambert.Peerra.Pages.Issues
{
    [Authorize]
    public class PeersModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly IUserIssueService _userIssueService;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public List<Issue> TargetedIssues { get; set; }
        public List<Issue> AllIssues { get; set; }

        public PeersModel(ApplicationDbContext context, IUserIssueService userIssueService, SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _userIssueService = userIssueService;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            var user = await _signInManager.UserManager.GetUserAsync(User);
            AllIssues = await _userIssueService.GetOthersIssuesAsync(user);
            TargetedIssues = await _userIssueService.GetOthersTargetedIssuesAsync(user);

            return Page();
        }
    }
}

Source/Pages/Issues/Respond.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using DrakeLambert.Peerra.Data;
using DrakeLambert.Peerra.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace DrakeLambert.Peerra.Pages.Issues
{
    [Authorize]
    public class RespondModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public Issue Issue { get; set; }

        [BindProperty]
        public HelpRequest HelpRequest { get; set; }

        public RespondModel(ApplicationDbContext context, SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> OnGetAsync([FromRoute] Guid id)
        {
            Issue = await _context.Issues
                .Include(i => i.HelpRequests)
                .Include(i => i.Owner)
                .Include(i => i.Topic)
                .SingleOrDefaultAsync(i => i.Id == id);

            if (Issue == null)
            {
                return RedirectToPage("/NotFound", new { message = "This issue may have been removed or moved." });
            }

            var user = await _signInManager.UserManager.GetUserAsync(User);

            if (user.Id == Issue.OwnerId)
            {
                return RedirectToPage("/Issues/Single", new { id = id });
            }

            HelpRequest = Issue.HelpRequests.SingleOrDefault(hr => hr.HelperId == user.Id);

            if (HelpRequest == null)
            {
                HelpRequest = new HelpRequest
                {
                    Helper = user,
                    Issue = Issue
                };

                Issue.HelpRequests.Add(HelpRequest);
            }

            await _context.SaveChangesAsync();

            return Page();
        }

        public async Task<IActionResult> OnPostAsync([FromRoute] Guid id)
        {
            Issue = await _context.Issues
                .Include(i => i.HelpRequests)
                .Include(i => i.Owner)
                .Include(i => i.Topic)
                .SingleOrDefaultAsync(i => i.Id == id);

            if (Issue == null)
            {
                return RedirectToPage("/NotFound", new { message = "This issue may have been removed or moved." });
            }

            var user = await _signInManager.UserManager.GetUserAsync(User);

            if (user.Id == Issue.OwnerId)
            {
                return RedirectToPage("/Issues/Single", new { id = id });
            }

            var existingHelpRequest = Issue.HelpRequests.SingleOrDefault(hr => hr.HelperId == user.Id);

            if (existingHelpRequest == null)
            {
                existingHelpRequest = new HelpRequest
                {
                    Helper = user,
                    Issue = Issue
                };

                Issue.HelpRequests.Add(existingHelpRequest);
            }

            existingHelpRequest.Message = HelpRequest.Message;
            existingHelpRequest.Status = HelpRequestStatus.Responded;

            await _context.SaveChangesAsync();

            return RedirectToPage("Peer", new { id = id });
        }
    }
}

Source/Pages/Issues/Single.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DrakeLambert.Peerra.Data;
using DrakeLambert.Peerra.Entities;
using DrakeLambert.Peerra.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace DrakeLambert.Peerra.Pages.Issues
{
    [Authorize]
    public class SingleModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<SingleModel> _logger;
        private readonly UserManager<ApplicationUser> _userManager;

        public Issue Issue { get; set; }
        public IEnumerable<HelpRequest> Responses => Issue.HelpRequests.Where(h => h.Status == HelpRequestStatus.Responded);

        public int RespondedCount => Responses.Count();
        public int PendingCount => Issue.HelpRequests.Where(h => h.Status == HelpRequestStatus.Pending).Count();
        public int DeclinedCount => Issue.HelpRequests.Count(h => h.Status == HelpRequestStatus.Declined);

        public SingleModel(ApplicationDbContext context, ILogger<SingleModel> logger, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _logger = logger;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync([FromRoute] Guid id)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToPage("/Error");
            }

            Issue = await _context.Issues
                .Include(i => i.Topic)
                .Include(i => i.HelpRequests)
                    .ThenInclude(h => h.Helper)
                .SingleOrDefaultAsync(i => i.Id == id);

            if (Issue == null || user.Id != Issue.OwnerId)
            {
                return RedirectToPage("/NotFound", new { message = "Your issue may have been removed or moved. Return home to view all your issues." });
            }

            foreach (var response in Responses)
            {
                response.HasBeenViewed = true;
            }

            await _context.SaveChangesAsync();

            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync([FromRoute] Guid id)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToPage("/Error");
            }

            Issue = await _context.Issues.FindAsync(id);

            if (Issue == null || user.Id != Issue.OwnerId)
            {
                return RedirectToPage("/NotFound", new { message = "Your issue may have been removed or moved. Return home to view all your issues." });
            }

            await _context.Entry(Issue).Collection(i => i.HelpRequests).LoadAsync();

            _context.RemoveRange(Issue.HelpRequests);
            _context.Remove(Issue);

            await _context.SaveChangesAsync();

            return RedirectToPage("/Index");
        }

        public async Task<IActionResult> OnPostSolvedAsync([FromRoute] Guid id)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToPage("/Error");
            }

            Issue = await _context.Issues.FindAsync(id);

            if (Issue == null || user.Id != Issue.OwnerId)
            {
                return RedirectToPage("/NotFound", new { message = "Your issue may have been removed or moved. Return home to view all your issues." });
            }

            await _context.Entry(Issue).Collection(i => i.HelpRequests).LoadAsync();

            Issue.IsSolved = true;

            _context.RemoveRange(Issue.HelpRequests.Where(h => h.Status == HelpRequestStatus.Pending));

            await _context.SaveChangesAsync();

            return RedirectToPage("Single", new { id = id });
        }

        public async Task<IActionResult> OnPostReOpenAsync([FromRoute] Guid id, [FromServices] IHelpRequestService helpRequestService)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToPage("/Error");
            }

            Issue = await _context.Issues.FindAsync(id);

            if (Issue == null || user.Id != Issue.OwnerId)
            {
                return RedirectToPage("/NotFound", new { message = "Your issue may have been removed or moved. Return home to view all your issues." });
            }

            Issue.IsSolved = false;

            await _context.Entry(Issue).Collection(i => i.HelpRequests).LoadAsync();

            if (Issue.HelpRequests.Where(hr => hr.Status != HelpRequestStatus.Declined).Count() == 0)
            {
                await helpRequestService.RequestHelpAsync(Issue);
            }

            await _context.SaveChangesAsync();

            return RedirectToPage("Single", new { id = id });
        }

        public async Task<IActionResult> OnPostMoreHelpAsync([FromRoute] Guid id, [FromServices] IHelpRequestService helpRequestService)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToPage("/Error");
            }

            Issue = await _context.Issues.FindAsync(id);

            if (Issue == null || user.Id != Issue.OwnerId)
            {
                return RedirectToPage("/NotFound", new { message = "Your issue may have been removed or moved. Return home to view all your issues." });
            }

            await helpRequestService.RequestHelpAsync(Issue);

            return RedirectToPage("Single", new { id = id });
        }
    }
}

Source/Pages/Issues/All.cshtml
@page
@model AllModel
@{
ViewData["Title"] = "My Issues";
}

<h1>My Issues</h1>
<p>All your issues can be found here.</p>
<hr>

<div class="row" style="margin: 0 -.5rem">
    <div class="col-sm-6 col-md-4 col-lg-3 px-2 pb-3 card-col">
        <a asp-page="/Topics/Start">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Add An Issue</h5>
                    <p class="card-text">Click here to start by selecting a topic.</p>
                </div>
            </div>
        </a>
    </div>
    @foreach (var issue in Model.MyIssues) {
    <div class="col-sm-6 col-md-4 col-lg-3 px-2 pb-3 card-col">
        <a asp-page="/Issues/Single" asp-route-id="@issue.Id">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@issue.Title</h5>
                    @if (issue.Description.Length > 100) {
                    <p class="card-text">@issue.Description.Substring(0, 100)...</p>
                    } else {
                    <p class="card-text">@issue.Description</p>
                    }
                </div>
            </div>
        </a>
    </div>
    }
</div>

Source/Pages/Issues/New.cshtml
@page "{id}"
@model NewModel
@{
ViewData["Title"] = "New Issue";
}

@if (Model.ParentTopic == null)
{
<h1>Describe Your Issue</h1>
<p><strong>Not selecting a topic for your issue will make it harder for us to find you help.</strong> We recommend searching for a parent topic using the <a asp-page="/Index">topic explorer</a> or the <a asp-page="/Topics/Search">topic search</a>. You can then submit your issue there.</p>
}
else
{
<h1>Describe Your Issue With @Model.ParentTopic.Title</h1>
<p>If you don't think your new topic belongs under @Model.ParentTopic.Title, use the <a asp-page="/Topics/Start">topic explorer</a> or the <a asp-page="/Topics/Search">topic search</a> to find the right parent topic.</p>
}

<hr>

<form method="POST" class="mb-3">
    <div class="form-group">
        <label asp-for="NewIssue.Title">Give Your Issue a Title</label>
        <input asp-for="NewIssue.Title" class="form-control" aria-describedby="titleHelp" placeholder="Enter title">
        <small id="titleHelp" class="form-text text-muted">Keep this short and simple.</small>
        <span class="text-danger form-text mt-0" asp-validation-for="NewIssue.Title"></span>
    </div>
    <div class="form-group">
        <label asp-for="NewIssue.Description">Describe Your Issue</label>
        <textarea asp-for="NewIssue.Description" class="form-control" aria-describedby="descriptionHelp" placeholder="Enter description" rows="3"></textarea>
        <small id="descriptionHelp" class="form-text text-muted">In two or three sentences, tell us about your issue.</small>
        <span class="text-danger form-text mt-0" asp-validation-for="NewIssue.Description"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Source/Pages/Issues/Peer.cshtml
@page "{id}"
@using Entities
@model PeerModel
@{
ViewData["Title"] = "Peer Issue";
}

<div class="row justify-content-between">
    <div class="col-md-auto">
        <h1 class="mb-md-0">@Model.Issue.Owner.UserName's Issue</h1>
    </div>
    <div class="col-md-auto">
        <div class="row row-dense align-items-center" style="height: 100%">
            @if (Model.Issue.IsSolved) {
            <div class="col-auto pb-0">
                <h3 class="text-success mb-0">Issue Solved!</h3>
            </div>
            } else {
            @if (Model.UserHelpRequest == null || Model.UserHelpRequest.Status == HelpRequestStatus.Pending) {
            <div class="col-auto pb-0">
                <a asp-page="Respond" asp-route-id="@Model.Issue.Id" class="btn btn-outline-success">Respond</a>
            </div>
            <div class="col-auto pb-0">
                <form method="post">
                    <button type="submit" asp-page-handler="decline" class="btn btn-outline-danger">Can't Help</button>
                </form>
            </div>
            } else if (Model.UserHelpRequest.Status == HelpRequestStatus.Declined) {
            <div class="col-auto pb-0">
                <h3 class="text-danger mb-0">Help Declined</h3>
            </div>
            } else {
            <div class="col-auto pb-0">
                <h3 class="text-success mb-0">Responded</h3>
            </div>
            }
            }
        </div>
    </div>
</div>

<hr>
<h4>@Model.Issue.Topic.Title</h4>
<h5>@Model.Issue.Title</h5>
<p>@Model.Issue.Description</p>

<hr>
@if (Model.Issue.HelpRequests.Where(h => h.Status == HelpRequestStatus.Responded ).Count() == 0) {
<h4 class="text-muted">Peer Responses Will Appear Here</h4>
}else {
<h4 class="mb-3" id="responses-title">Responses:</h4>
}
@foreach (var request in Model.Issue.HelpRequests.Where(h => h.Status == HelpRequestStatus.Responded )) {
<hr>
<div class="row justify-content-between align-items-center">
    <div class="col-auto">
        <h5><span class="text-muted">From: </span> @request.Helper.UserName</h5>
    </div>
</div>
<p>@request.Message</p>
}

<style>
    #responses-title+hr {
        display: none;
    }
</style>

Source/Pages/Issues/Peers.cshtml
@page
@model PeersModel
@{
ViewData["Title"] = "Peer Issues";
}

<h1>Help Your Peers</h1>

<hr>

<h3>Issues For You</h3>
<p>Based on your experience, we think you'll be able to help with these issues.</p>

@if (Model.TargetedIssues.Count == 0) {
<h5 class="text-muted">When your peers have issues you can solve, they'll show up here.</h5>
} else {
<div class="list-group mb-3">
	@foreach (var issue in Model.TargetedIssues) {
	<a asp-page="/Issues/Peer" asp-route-id="@issue.Id" class="list-group-item list-group-item-action">
		<h5>@issue.Topic.Title: @issue.Title</h5>
		<p class="mb-0">@issue.Description</p>
	</a>
	}
</div>
}
<a asp-page="/Topics/Knowledge" class="btn btn-outline-success mt-2">Improve Suggestions</a>

<hr>

<h3>All Issues</h3>
<p>See all of your peers' unsolved issues.</p>
@if (Model.AllIssues.Count == 0) {
<h5 class="text-muted">When your peers have issues you can solve, they'll show up here.</h5>
} else {
<div class="list-group mb-3">
	@foreach (var issue in Model.AllIssues) {
	<a asp-page="/Issues/Peer" asp-route-id="@issue.Id" class="list-group-item list-group-item-action">
		<h5>@issue.Topic.Title: @issue.Title</h5>
		<p class="mb-0">@issue.Description</p>
	</a>
	}
</div>
}

Source/Pages/Issues/Respond.cshtml
@page "{id}"
@model RespondModel
@{
ViewData["Title"] = "Respond";
}

<h1>Respond to @Model.Issue.Owner.UserName</h1>
<hr>
<h4>@Model.Issue.Topic.Title</h4>
<h5>@Model.Issue.Title</h5>
<p>@Model.Issue.Description</p>
<hr>

<form method="POST" class="mb-3">
    <div class="form-group">
        <label asp-for="HelpRequest.Message">Your Response</label>
        <textarea asp-for="HelpRequest.Message" class="form-control" aria-describedby="messageHelp" placeholder="Here's how I can help..." rows="3"></textarea>
        <small id="messageHelp" class="form-text text-muted">In two or three sentences, try to give the best help you can. @Model.Issue.Owner.UserName will be able to email you for more help.</small>
        <span class="text-danger form-text mt-0" asp-validation-for="HelpRequest.Message"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Source/Pages/Issues/Single.cshtml
@page "{id}"
@using Entities
@model SingleModel
@{
ViewData["Title"] = "My Issue";
Model.Issue.HelpRequests.Sort((x, y) => (int)x.Status - (int)y.Status);
}

<div class="row justify-content-between">
	<div class="col-md-auto">
		@if (Model.Issue.IsSolved) {
		<h1>You've Solved This Issue!</h1>
		<p>Re-Open this issue to request more help.</p>
		} else {
		<h1>Getting You Help Now...</h1>
		<p class="mb-3">
			We've sent your issue to @Model.Issue.HelpRequests.Count of your peers.
		</p>
		}
	</div>
	<div class="col-md-auto">
		<div class="row row-dense align-items-center" style="height: 100%">
			<div class="col-auto">
				@if (Model.Issue.IsSolved) {
				<form method="post">
					<button type="submit" asp-page-handler="reopen" class="btn btn-outline-success">Re-Open</button>
				</form>
				} else {
				<form method="post">
					<button type="submit" asp-page-handler="solved" class="btn btn-outline-success">Mark Solved</button>
				</form>
				}
			</div>
			<div class="col-auto">
				<form method="post">
					<button type="submit" asp-page-handler="delete" class="btn btn-outline-danger">Delete Issue</button>
				</form>
			</div>
		</div>
	</div>
</div>

<hr class="mt-0">

<div class="row">
	<div class="col-md-8">
		@if (Model.RespondedCount == 0) {
		<h4 class="text-muted">Responses Will Appear Here</h4>
		}
		@foreach (var request in Model.Issue.HelpRequests.Where(h => h.Status == HelpRequestStatus.Responded )) {
		<div class="row justify-content-between align-items-center">
			<div class="col-auto">
				<h5><span class="text-muted">From: </span> @request.Helper.UserName</h5>
			</div>
			<div class="col-auto">
				<a href="mailto:@request.Helper.Email?subject=@request.Issue.Title" class="btn btn-outline-primary mb-2">Email</a>
			</div>
		</div>
		<p>@request.Message</p>
		<hr>
		}
	</div>
	<div class="col-md-4">
		<hr class="d-md-none">
		<h4>@Model.Issue.Topic.Title</h4>
		<h5>@Model.Issue.Title</h5>
		<p>@Model.Issue.Description</p>
		@if (!Model.Issue.IsSolved) {
		<hr class="mt-0">
		<div class="row justify-content-between align-items-center">
			<div class="col-auto">
				<h4>Help Requests</h4>
			</div>
			<div class="col-auto">
				<form method="post">
					<button type="submit" asp-page-handler="morehelp" class="btn btn-outline-primary mb-2">More Help</button>
				</form>
			</div>
		</div>
		<table class="table table-sm">
			<tbody>
				@foreach (var request in Model.Issue.HelpRequests) {
				@if (request.Status != HelpRequestStatus.Declined) {
				<tr>
					<td>@request.Helper.UserName</td>
					<td style="text-align: right;">
						@if (request.Status == HelpRequestStatus.Responded) {
						<span class="text-success">Responded</span>
						} else {
						<span>Pending</span>
						}
					</td>
				</tr>
				}
				}
			</tbody>
		</table>
		}
	</div>
</div>